/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { RankUserService } from "../rankUser.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { RankUserCreateInput } from "./RankUserCreateInput";
import { RankUser } from "./RankUser";
import { RankUserFindManyArgs } from "./RankUserFindManyArgs";
import { RankUserWhereUniqueInput } from "./RankUserWhereUniqueInput";
import { RankUserUpdateInput } from "./RankUserUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class RankUserControllerBase {
  constructor(
    protected readonly service: RankUserService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: RankUser })
  @nestAccessControl.UseRoles({
    resource: "RankUser",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createRankUser(
    @common.Body() data: RankUserCreateInput
  ): Promise<RankUser> {
    return await this.service.createRankUser({
      data: {
        ...data,

        rankUser: data.rankUser
          ? {
              connect: data.rankUser,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        description: true,
        id: true,
        point: true,
        rankLevel: true,
        rankName: true,

        rankUser: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [RankUser] })
  @ApiNestedQuery(RankUserFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "RankUser",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async rankUsers(@common.Req() request: Request): Promise<RankUser[]> {
    const args = plainToClass(RankUserFindManyArgs, request.query);
    return this.service.rankUsers({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,
        point: true,
        rankLevel: true,
        rankName: true,

        rankUser: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: RankUser })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "RankUser",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async rankUser(
    @common.Param() params: RankUserWhereUniqueInput
  ): Promise<RankUser | null> {
    const result = await this.service.rankUser({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,
        point: true,
        rankLevel: true,
        rankName: true,

        rankUser: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: RankUser })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "RankUser",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateRankUser(
    @common.Param() params: RankUserWhereUniqueInput,
    @common.Body() data: RankUserUpdateInput
  ): Promise<RankUser | null> {
    try {
      return await this.service.updateRankUser({
        where: params,
        data: {
          ...data,

          rankUser: data.rankUser
            ? {
                connect: data.rankUser,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          description: true,
          id: true,
          point: true,
          rankLevel: true,
          rankName: true,

          rankUser: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: RankUser })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "RankUser",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteRankUser(
    @common.Param() params: RankUserWhereUniqueInput
  ): Promise<RankUser | null> {
    try {
      return await this.service.deleteRankUser({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,
          point: true,
          rankLevel: true,
          rankName: true,

          rankUser: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
