version: "3.3"
services:
  user:
    build:
      context: .
      args:
        NPM_LOG_LEVEL: notice
    ports:
      - ${PORT}:8000
    volumes:
      - .:/app  # Mount the current directory to the /app directory inside the container
      - /app/node_modules
    environment:
      BCRYPT_SALT: ${BCRYPT_SALT}
      DB_URL: mongodb://${DB_USER}:${DB_PASSWORD}@db:27017/${DB_NAME}?authSource=admin
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      RABBITMQ_URLS: ${RABBITMQ_URLS}
    depends_on:
      db:
        condition: service_healthy
      # rabbitmq:
      #   condition: service_healthy
    restart: on-failure
    networks:
      - app-network

  migrate:
    build:
      context: .
      args:
        NPM_LOG_LEVEL: notice
    command: npm run db:init
    working_dir: /app/user
    environment:
      BCRYPT_SALT: ${BCRYPT_SALT}
      DB_URL: mongodb://${DB_USER}:${DB_PASSWORD}@db:27017/${DB_NAME}?authSource=admin
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mongo
    ports:
      - ${DB_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_REPLICA_SET_NAME: rs0
    restart: always
    entrypoint:
      - /bin/bash
      - -c
      - openssl rand -base64 741 > /data/cert.crt; chmod 400 /data/cert.crt &&
        chown 999 /data/cert.crt; /usr/local/bin/docker-entrypoint.sh mongod
        --bind_ip_all --keyFile /data/cert.crt --replSet rs0
    healthcheck:
      test: "test $$(mongosh --quiet -u  $${MONGO_INITDB_ROOT_USERNAME} -p
        $${MONGO_INITDB_ROOT_PASSWORD} --eval \"try { rs.initiate({ _id:
        'rs0',members: [{ _id: 0, host: 'db' }] }).ok } catch (_) {
        rs.status().ok}\") -eq 1"
      start_period: 5s
      interval: 10s
      timeout: 10s
    volumes:
      - mongo_data:/data/db # Lưu dữ liệu MongoDB tại volume `mongo_data`
      - mongo_config:/data/configdb # Lưu trữ cấu hình MongoDB
    networks:
      - app-network

networks:
  app-network:
    external: true  

volumes:
  mongo_data:
    external: false # Volume lưu dữ liệu MongoDB
  mongo_config:
    external: false # Volume lưu cấu hình MongoDB
