/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { OutBoxService } from "../outBox.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { OutBoxCreateInput } from "./OutBoxCreateInput";
import { OutBox } from "./OutBox";
import { OutBoxFindManyArgs } from "./OutBoxFindManyArgs";
import { OutBoxWhereUniqueInput } from "./OutBoxWhereUniqueInput";
import { OutBoxUpdateInput } from "./OutBoxUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class OutBoxControllerBase {
  constructor(
    protected readonly service: OutBoxService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: OutBox })
  @nestAccessControl.UseRoles({
    resource: "OutBox",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createOutBox(@common.Body() data: OutBoxCreateInput): Promise<OutBox> {
    return await this.service.createOutBox({
      data: data,
      select: {
        createdAt: true,
        eventType: true,
        id: true,
        payload: true,
        processedDate: true,
        retry: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [OutBox] })
  @ApiNestedQuery(OutBoxFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "OutBox",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async outBoxes(@common.Req() request: Request): Promise<OutBox[]> {
    const args = plainToClass(OutBoxFindManyArgs, request.query);
    return this.service.outBoxes({
      ...args,
      select: {
        createdAt: true,
        eventType: true,
        id: true,
        payload: true,
        processedDate: true,
        retry: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: OutBox })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "OutBox",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async outBox(
    @common.Param() params: OutBoxWhereUniqueInput
  ): Promise<OutBox | null> {
    const result = await this.service.outBox({
      where: params,
      select: {
        createdAt: true,
        eventType: true,
        id: true,
        payload: true,
        processedDate: true,
        retry: true,
        status: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: OutBox })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "OutBox",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateOutBox(
    @common.Param() params: OutBoxWhereUniqueInput,
    @common.Body() data: OutBoxUpdateInput
  ): Promise<OutBox | null> {
    try {
      return await this.service.updateOutBox({
        where: params,
        data: data,
        select: {
          createdAt: true,
          eventType: true,
          id: true,
          payload: true,
          processedDate: true,
          retry: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: OutBox })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "OutBox",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteOutBox(
    @common.Param() params: OutBoxWhereUniqueInput
  ): Promise<OutBox | null> {
    try {
      return await this.service.deleteOutBox({
        where: params,
        select: {
          createdAt: true,
          eventType: true,
          id: true,
          payload: true,
          processedDate: true,
          retry: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
